name: Deploy S3 and SNS app to ECR

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push s3-app
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          S3_ECR_REPOSITORY: ${{ secrets.S3_ECR_REPOSITORY }}
        run: |
          echo "ECR_REGISTRY: $ECR_REGISTRY"
          echo "S3_ECR_REPOSITORY: $S3_ECR_REPOSITORY"
          docker build -t $ECR_REGISTRY/$S3_ECR_REPOSITORY:latest ./s3-app
          docker push $ECR_REGISTRY/$S3_ECR_REPOSITORY:latest

      - name: Build and push sns-app
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SQS_ECR_REPOSITORY: ${{ secrets.SQS_ECR_REPOSITORY }}
        run: |
          echo "ECR_REGISTRY: $ECR_REGISTRY"
          echo "SQS_ECR_REPOSITORY: $SQS_ECR_REPOSITORY"
          docker build -t $ECR_REGISTRY/$SQS_ECR_REPOSITORY:latest ./sns-app
          docker push $ECR_REGISTRY/$SQS_ECR_REPOSITORY:latest
